Author: Aya Abdelsalam Ismail, Mohamed Gunady, Hector Corrada Bravo*, Soheil Feizi
Repository: https://github.com/ayaabdelsalam91/TS-Interpretability-Benchmark
Accessed: July 29, 2023

hidden_size: 5
num_classes: 2
rnndropout: 0.1
learning_rate: 0.01
batch_size: 50
num_epochs: 500
n_layers: 6
heads: 5
method: IGFlag
Precision_Recall_dir: Precision_Recall
timeflag: False
featureflag: False
sampler: irregular
frequency: 2.0
kernel: Matern
ar_param: 0.9
order: 10
has_noise: True
num_features: 50
num_time_steps: 50
iterations: 5
